//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wtiau.Health.Web.Models.Domian
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_College
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_College()
        {
            this.Tbl_Grad = new HashSet<Tbl_Grad>();
        }
    
        public int College_ID { get; set; }
        public System.Guid College_Guid { get; set; }
        public int College_UniversityID { get; set; }
        public string College_Display { get; set; }
        public bool College_IsDelete { get; set; }
    
        public virtual Tbl_University Tbl_University { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Grad> Tbl_Grad { get; set; }
    }
}
