//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wtiau.Health.Web.Models.Domian
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Question
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Question()
        {
            this.Tbl_Response = new HashSet<Tbl_Response>();
        }
    
        public int Question_ID { get; set; }
        public System.Guid Question_Guid { get; set; }
        public int Question_FSID { get; set; }
        public int Question_FormID { get; set; }
        public string Question_Title { get; set; }
        public int Question_TypeCodeID { get; set; }
        public bool Question_Lie { get; set; }
        public bool Question_IsDelete { get; set; }
    
        public virtual Tbl_Code Tbl_Code { get; set; }
        public virtual Tbl_Form Tbl_Form { get; set; }
        public virtual Tbl_FormStep Tbl_FormStep { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Response> Tbl_Response { get; set; }
    }
}
