//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wtiau.Health.Web.Models.Domian
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Login
    {
        public int Login_ID { get; set; }
        public System.Guid Login_Guid { get; set; }
        public int Login_RoleID { get; set; }
        public string Login_Email { get; set; }
        public string Login_Name { get; set; }
        public string Login_Family { get; set; }
        public string Login_PasswordHash { get; set; }
        public string Login_PasswordSalt { get; set; }
        public System.DateTime Login_CreateDate { get; set; }
        public System.DateTime Login_Modify { get; set; }
        public string Login_Mobile { get; set; }
        public bool Login_IsDelete { get; set; }
    
        public virtual Tbl_Role Tbl_Role { get; set; }
    }
}
