//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wtiau.Health.Web.Models.Domian
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Response
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Response()
        {
            this.Tbl_FormAnswerResponse = new HashSet<Tbl_FormAnswerResponse>();
        }
    
        public int Response_ID { get; set; }
        public System.Guid Response_Guid { get; set; }
        public int Response_QuestionID { get; set; }
        public string Response_Title { get; set; }
        public int Response_Hint { get; set; }
        public int Response_Order { get; set; }
        public bool Response_IsTrue { get; set; }
        public bool Response_IsDelete { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_FormAnswerResponse> Tbl_FormAnswerResponse { get; set; }
        public virtual Tbl_Question Tbl_Question { get; set; }
    }
}
