//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wtiau.Health.Web.Models.Domian
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Code
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Code()
        {
            this.Tbl_Question = new HashSet<Tbl_Question>();
            this.Tbl_StudentInfo = new HashSet<Tbl_StudentInfo>();
            this.Tbl_StudentInfo1 = new HashSet<Tbl_StudentInfo>();
            this.Tbl_StudentInfo2 = new HashSet<Tbl_StudentInfo>();
            this.Tbl_StudentInfo3 = new HashSet<Tbl_StudentInfo>();
            this.Tbl_StudentInfo4 = new HashSet<Tbl_StudentInfo>();
            this.Tbl_StudentInfo5 = new HashSet<Tbl_StudentInfo>();
            this.Tbl_StudentInfo6 = new HashSet<Tbl_StudentInfo>();
        }
    
        public int Code_ID { get; set; }
        public System.Guid Code_Guid { get; set; }
        public int Code_CGID { get; set; }
        public string Code_Name { get; set; }
        public string Code_Display { get; set; }
        public bool Code_IsActive { get; set; }
        public bool Code_IsDelete { get; set; }
    
        public virtual Tbl_CodeGroup Tbl_CodeGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Question> Tbl_Question { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_StudentInfo> Tbl_StudentInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_StudentInfo> Tbl_StudentInfo1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_StudentInfo> Tbl_StudentInfo2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_StudentInfo> Tbl_StudentInfo3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_StudentInfo> Tbl_StudentInfo4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_StudentInfo> Tbl_StudentInfo5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_StudentInfo> Tbl_StudentInfo6 { get; set; }
    }
}
