//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wtiau.Health.Web.Models.Domian
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Turn
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Turn()
        {
            this.Tbl_TurnTimeSheet = new HashSet<Tbl_TurnTimeSheet>();
        }
    
        public int Turn_ID { get; set; }
        public System.Guid Turn_Guid { get; set; }
        public string Turn_Name { get; set; }
        public string Turn_Description { get; set; }
        public bool Turn_IsActive { get; set; }
        public bool Turn_IsDelete { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_TurnTimeSheet> Tbl_TurnTimeSheet { get; set; }
    }
}
