//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wtiau.Health.Web.Models.Domian
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_StudentInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_StudentInfo()
        {
            this.Tbl_Student = new HashSet<Tbl_Student>();
        }
    
        public int SI_ID { get; set; }
        public System.Guid SI_Guid { get; set; }
        public string SI_Name { get; set; }
        public string SI_Family { get; set; }
        public string SI_Email { get; set; }
        public string SI_Phone { get; set; }
        public string SI_Mobile { get; set; }
        public int SI_GenderCodeID { get; set; }
        public int SI_BirthYearCodeID { get; set; }
        public int SI_NationalCodeID { get; set; }
        public int SI_BloodCodeID { get; set; }
        public int SI_InsuranceCodeID { get; set; }
        public int SI_HomeTypeCodeID { get; set; }
        public int SI_MarriageCodeID { get; set; }
        public int SI_BranchID { get; set; }
        public string SI_BirthdayLocation { get; set; }
        public string SI_BeforeUniversity { get; set; }
        public bool SI_IsDelete { get; set; }
    
        public virtual Tbl_Branch Tbl_Branch { get; set; }
        public virtual Tbl_Code Tbl_Code { get; set; }
        public virtual Tbl_Code Tbl_Code1 { get; set; }
        public virtual Tbl_Code Tbl_Code2 { get; set; }
        public virtual Tbl_Code Tbl_Code3 { get; set; }
        public virtual Tbl_Code Tbl_Code4 { get; set; }
        public virtual Tbl_Code Tbl_Code5 { get; set; }
        public virtual Tbl_Code Tbl_Code6 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Student> Tbl_Student { get; set; }
    }
}
