//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wtiau.Health.Web.Models.Domian
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_FormAnswer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_FormAnswer()
        {
            this.Tbl_FormAnswerResponse = new HashSet<Tbl_FormAnswerResponse>();
        }
    
        public int FA_ID { get; set; }
        public System.Guid FA_Guid { get; set; }
        public int FA_StudentID { get; set; }
        public int FA_FormID { get; set; }
        public bool FA_IsDelete { get; set; }
    
        public virtual Tbl_Form Tbl_Form { get; set; }
        public virtual Tbl_Student Tbl_Student { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_FormAnswerResponse> Tbl_FormAnswerResponse { get; set; }
    }
}
