//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wtiau.Health.Web.Models.Domian
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Form
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Form()
        {
            this.Tbl_FormAnswer = new HashSet<Tbl_FormAnswer>();
            this.Tbl_FormStep = new HashSet<Tbl_FormStep>();
            this.Tbl_Question = new HashSet<Tbl_Question>();
        }
    
        public int Form_ID { get; set; }
        public System.Guid Form_Guid { get; set; }
        public string Form_Name { get; set; }
        public int Form_CourseID { get; set; }
        public string Form_Display { get; set; }
        public bool Form_IsActive { get; set; }
        public System.DateTime Form_CreateDate { get; set; }
        public System.DateTime Form_ModifyDate { get; set; }
        public bool Form_IsDelete { get; set; }
    
        public virtual Tbl_Course Tbl_Course { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_FormAnswer> Tbl_FormAnswer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_FormStep> Tbl_FormStep { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Question> Tbl_Question { get; set; }
    }
}
